//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.PaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/balancecheck", ReplyAction="http://tempuri.org/IService/balancecheckResponse")]
        string balancecheck(int accno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/balancecheck", ReplyAction="http://tempuri.org/IService/balancecheckResponse")]
        System.Threading.Tasks.Task<string> balancecheckAsync(int accno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/balanceupdate", ReplyAction="http://tempuri.org/IService/balanceupdateResponse")]
        int balanceupdate(string accno, string newbal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/balanceupdate", ReplyAction="http://tempuri.org/IService/balanceupdateResponse")]
        System.Threading.Tasks.Task<int> balanceupdateAsync(string accno, string newbal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : project.PaymentService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<project.PaymentService.IService>, project.PaymentService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string balancecheck(int accno) {
            return base.Channel.balancecheck(accno);
        }
        
        public System.Threading.Tasks.Task<string> balancecheckAsync(int accno) {
            return base.Channel.balancecheckAsync(accno);
        }
        
        public int balanceupdate(string accno, string newbal) {
            return base.Channel.balanceupdate(accno, newbal);
        }
        
        public System.Threading.Tasks.Task<int> balanceupdateAsync(string accno, string newbal) {
            return base.Channel.balanceupdateAsync(accno, newbal);
        }
    }
}
